#
# config file used for development.
#

server:
  port: 8080

spring:
  application:
    name: pos-service
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3309/poi?useSSL=false
    password: hello

reqres:
  url: "https://reqres.in"
  path: "/api/users"
  readTimeout: 5000
  connectionTimeout: 1000


logging:
  level:
    ROOT: INFO
    org.springframework.web: ERROR
    nl.vz.poi.engine: TRACE
  file:
    name: logs/poi-service.gz



